### ISSUE TITLE
flex布局的一些细节

### ISSUE THREAD

**Issue by CooperHash** [CooperHash/CSS-Wiki#1]
flex属性是这样的：flex-grow | flex-shirink | flex-basis
第一个属性flex-grow是个数字，如果不为0，在会在屏幕宽度发生拉长的时候，item 在 flex-basis 的基础上进行拉伸
<img src="https://cdn.homeblog.top/uPic/ZSIl9B.png"/>
可以看到item 1 的左侧的阴影部分就是flex-basis，右边的部分就是后来拉伸的
如果是要设置一个三列布局，三个部分之间的比例通过flex-grow可以设置，

```html
<div class="out">
 <div class="in">1</div>
 <div class="in">2</div>
 <div class="in">3</div>
</div>
```

```css
.out {
 display: flex;
 flex-wrap: wrap;
}

.out:nth-child(1) {
 height: 15vh;
 flex: 2 1 150px;
}

.out:nth-child(2) {
 height: 15vh;
 flex: 1 1 150px;
}

out:nth-child(3) {
 height: 15vh;
 flex: 1 1 150px;
}
```

这里三个部分的比例就是 2 ： 1  ：1
能维持这个比例的前提是：外层宽度足够
