### ISSUE TITLE
Ten modern css layout

### ISSUE THREAD

**Issue by CooperHash** [CooperHash/CSS-Wiki#3]
一、超级居中
```html
<div class="parent" >
  <div class="child" contenteditable>:)</div>
</div>
```
```css
.parent {
 display: grid;
 place-item: center;
}
```
<br>

二、多列
```html
<div class="parent">
  <div class="child">1</div>
  <div class="child">2</div>
  <div class="child">3</div>
</div>
```
```css
.parent {
 display: flex;
 flex-wrap: wrap;
}

.child {
 flex: 0 1 300px;
 flex: 1 1 300px;
}
```
如果想要子 item 进行伸展的话，flex-grow就不能是0
<br>
三、两栏布局
左边一栏在屏幕宽度不大的情况下，保持着最小的150px，屏幕宽度允许，就展示为25%
```css
 display: grid;
 grid-template-columns: minmax(150px, 25%) 1fr;
```
<br>
四、上中下固定
```css
 display: grid;
 grid-template-rows: auto 1fr auto;
```

<br>
五、圣杯布局

---
*参考*
<div><a href="https://1linelayouts.glitch.me/">1linelayouts</div>
